version: "3"

services:
  app:
    build: .
    restart: always
    command: npm run dev
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    volumes:
      - .:/usr/app
    external_links:
      - db
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    container_name: ${DB_CONTAINER_HOST}
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_CONTAINER_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_CONTAINER_NAME}
      - MYSQL_TCP_PORT=${DB_CONTAINER_PORT}
    ports:
      - '${DB_LOCAL_PORT}:${DB_CONTAINER_PORT}'
    volumes:
      - db:/var/lib/mysql
volumes: 
  db: