version: "3"

services:
  app:
    build: .
    command: npm run dev
    ports:
      - 4000:4000
    volumes:
      - .:/usr/app
    depends_on:
      - db
  db:
    container_name: 'database-node'
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=recipes
    stdin_open: true
    tty: true